[tool.poetry]
name = "mlflow-pet-new"
version = "0.1.0"
description = ""
authors = ["66910 <669101mac@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
mlflow = "^2.14.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
